# Project information
site_name: 'Tegola User Guide'
site_description: 'MkDocs Material Boilerplate (Starter Kit) - Deploy documentation to hosting platforms (Netlify, GitHub Pages, GitLab Pages, and AWS Amplify Console) with Docker, pipenv, and GitHub Actions.'
site_author: 'peaceiris'
site_url: 'https://docs.tegola.lk/'

# Copyright
copyright: '&copy; 2021 Heavenz Technologies'

# Configuration
docs_dir: 'docs_sample'
theme:
  name: 'material'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    scheme: 'preference'
  features:
    - navigation.tabs
    - tabs
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  logo: 'images/logo.svg'
  favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
extra:
  manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/heavenz'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/HeavenzLK'

# Page tree
nav:
  - 'How Tegola Works': 'how-tegola-works.md'
  - 'Growing With Tegola': 'growing-with-tegola.md'
  - 'FAQ': 'frequently-asked-questions.md'
  - 'Creating Accounts':
    - 'Account Types': 'creating-accounts/account-types.md'
    - 'Create Professional Accounts': 'creating-accounts/professional.md'
    - 'Create Company Accounts': 'creating-accounts/company.md'
    - 'Create Individual Accounts': 'creating-accounts/individual.md'
    - 'Create Fresh Graduate Accounts': 'creating-accounts/fresh-graduate.md'
    - 'Create Undergraduate Accounts': 'creating-accounts/undergraduate.md'
  - 'Completing Profiles':
    - 'Features': 'completing-profiles/features.md'
  - 'Search Results':
    - 'Find a match': 'search-results/find-a-match.md'
  - 'Company Accounts':
    - 'Paid Membership': 'company-accounts/paid-membership.md'
    - 'Features': 'company-accounts/features.md'
