# Project information
site_name: 'Tegola User Guide'
site_description: 'A knowledgebase of everything related to Tegola.lk online platform.'
site_author: 'heavenz'
site_url: 'https://docs.tegola.lk/'

google_analytics:
  - UA-195326851-1
  - auto


# Copyright
copyright: '&copy; 2021 Heavenz Technologies Private Limited'

# Configuration
docs_dir: 'docs_sample'
theme:
  name: 'material'
  custom_dir: 'theme_overrides/'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    scheme: 'preference'
  features:
    - navigation.tabs
    - tabs
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  logo: 'images/logo.svg'
  favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - def_list
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'assets/js/custom.js'
extra_css:
  - 'assets/css/custom.css'
extra:
  manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/facebook'
      link: 'https://facebook.com/tegola.lk'
    - icon: 'fontawesome/brands/instagram'
      link: 'https://instagram.com/tegola.lk'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://linkedin.com/company/tegolalk'

# Page tree
nav:
  - 'How Tegola Works': 'how-tegola-works.md'
  - 'Growing With Tegola': 'growing-with-tegola.md'
  - 'FAQ': 'frequently-asked-questions.md'
  - 'Creating Accounts':
    - 'Account Types': 'creating-accounts/account-types.md'
    - 'Creating Professional Accounts': 'creating-accounts/professional.md'
    - 'Creating Company Accounts': 'creating-accounts/company.md'
    - 'Creating Individual Accounts': 'creating-accounts/individual.md'
    - 'Creating Fresh Graduate Accounts': 'creating-accounts/fresh-graduate.md'
    - 'Creating Undergraduate Accounts': 'creating-accounts/undergraduate.md'
  - 'Completing Profiles':
    - 'Features in Your Account': 'completing-profiles/features.md'
  - 'Search Results':
    - 'Finding a Match': 'search-results/finding-a-match.md'
  - 'Company Accounts':
    - 'Paid Membership': 'company-accounts/paid-membership.md'
    - 'Features': 'company-accounts/features.md'
